---
- hosts: all
  remote_user: pi
  sudo: no
  
  vars:
    flasher_install_dir: /home/pi/flasher
    flasher_version: master

  tasks:
    
#    - name: stop flasher
#      service: name=flasher state=stopped    
#      sudo: yes
      
    - name: download flasher from git
      git: repo=git://github.com/glynnbird/flasher.git dest={{ flasher_install_dir }} accept_hostkey=yes version={{ flasher_version }} update=yes

    - name: install flasher npm modules
      npm: path={{ flasher_install_dir }}
      
    - name: copy flasherdaemon.sh script
      copy: src=scripts/flasherdaemon.sh dest=/home/pi/flasher/flasherdaemon.sh owner=pi group=pi mode=755      
        
    - name: copy init.d script
      copy: src=scripts/flasher dest=/etc/init.d owner=root group=root mode=755
      sudo: yes
      
    - name: start flasher
      service: name=flasher state=started enabled=yes    
      sudo: yes    

