---
- hosts: all
  remote_user: pi
  sudo: no
  
  vars:
    couchdb_dev_dir: /home/pi/couchdb/dev 
    couchdb_etc_dir: /home/pi/couchdb/dev/lib/node1/etc
    couchdb_home: /home/pi/couchdb  
  
  tasks:
 
    - name: create directoy
      file: path={{ couchdb_etc_dir}} state=directory
 
    - name: copy customised vm.args file
      template: src=conf/vm.args dest={{ couchdb_etc_dir}}
      
    - name: copy customised dev/run script
      copy: src=scripts/run dest={{ couchdb_dev_dir }} owner=pi group=pi mode=755       

    - name: copy init.d script
      copy: src=scripts/couchdb dest=/etc/init.d owner=root group=root mode=755
      sudo: yes
      
    - name: start couchdb
      service: name=couchdb state=started enabled=yes    
      sudo: yes